language: node_js
node_js:
  - "node"
jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: npm run build
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      script: npm run lint
